<?php
/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
$assetDir = Yii::$app->assetManager->getPublishedUrl('@themes/rn500-theme');
?>

<section class="inner-banner">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <h1>Privacy Policy</h1>
            </div>
        </div>

    </div>
</section>

<section class="about-us about-inner-block">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-12 main-title">
                <h2 class="mb-4">Privacy Policy</h2>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">RN500, LLC. (referred to as &ldquo;RN500&rdquo;, &ldquo;us&rdquo;, &ldquo;we&rdquo;, or &ldquo;our&rdquo;) operates the RN500 website available at https://www.RN500.com/ and/or mobile applications (together, the &ldquo;Website&rdquo;) including the services available through the Website or via text messages (the &quot;Service&quot;).</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">This privacy policy (&ldquo;Policy&rdquo;) informs you of our policies regarding the collection, use and disclosure of Personal Information when you use our Service. Please read this Policy carefully to understand our policies and practices regarding your information and how we will treat it.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">If you do not agree with any of this Policy not use or access this Website.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">This Policy may change from time to time. We reserve the right, at our discretion to change, modify, add or remove portions of this Policy at any time. Your continued use of this Website after we make changes is deemed to be acceptance of those changes, so please check this Policy periodically for updates.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">We may offer you the ability to connect with the Website using a mobile device via a mobile optimized website. The provisions of this Policy apply to all such mobile access and use of mobile devices. This Policy will be referenced by all such mobile applications or mobile optimized websites.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><strong><span style="font-size:19px;color:black;">JURISDICTION&nbsp;</span></strong></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">This Website is intended for and available to users who reside in the United States or any of its territories or possessions only. If you reside in a jurisdiction outside the United States and its territories and possessions, you submit to the processing of your information in accordance with the laws of the United States and its territories and possessions, regardless of any conflicting provisions applicable in your country of residence.&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><strong><span style="font-size:19px;color:black;">INFORMATION COLLECTION AND USE&nbsp;</span></strong></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">While using our Service, we may ask you to provide us with certain information including information:&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <ul style="margin-bottom:0in;margin-top:0in;" type="disc">
                    <li style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;">by which you may be personally identified, such as your name, state of residence, e-mail address, telephone number, license, date of birth, last four digits of your social security number, email address, or any other information the Website collects or you provide RN500 through the Website or via text message that is defined by applicable law as personally identifiable information (collectively, &quot;Personal Information&quot;);</span></li>
                    <li style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;">that is about you but individually does not identify you, such as your IP address, metadata or physical location; and/or&nbsp;</span></li>
                    <li style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;">about your internet connection, telephone carrier, the equipment you use to access our Website and usage details.</span></li>
                </ul>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">We collect this information for the purpose of providing the Service, identifying and communicating with you, responding to your requests/inquiries, sharing job opportunities, servicing your applications, and improving our services.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">We collect certain information from and about our visitors and customers in three ways &ndash; directly from the user, from our web server logs, and through the use of tracking technologies (e.g., cookies, web beacons), such as -&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <ul style="margin-bottom:0in;margin-top:0in;" type="disc">
                    <li style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;">Directly from you when you provide it to us either through filling in forms on our Website, communicating with us via email communications, any correspondence via text messages, speaking with our representatives over the telephone, interacting with us via live chat or by using our Services. We may also ask you for information when you report a problem with our Website or the Service.</span></li>
                    <li style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;">Directly from you when you speak with our representative (via telephone or live chat) including when you provide personal information for verification purposes, for using the Services.&nbsp;</span></li>
                    <li style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;">Automatically as you navigate through the Website. Information collected automatically may include usage details, IP addresses, and information collected through cookies, web beacons, and other tracking technologies.</span></li>
                </ul>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><u><span style="font-size:19px;color:black;">Log Data</span></u></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">We collect information that your browser sends whenever you visit our Service (&quot;Log Data&quot;). This Log Data may include information such as your computer&apos;s Internet Protocol (&quot;IP&quot;) address, browser type, browser version, pages of our Website that you visit, time and date of your visit, time spent on those pages and other statistics.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">When you access the Service by or through a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile device&rsquo;s unique device ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, your location information and other statistics.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><u><span style="font-size:19px;color:black;">Location Information</span></u></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">We may use and store information about your location depending on the permissions you have set on your device / browser. We use this information to provide features of our Service, and to improve and customize our Service. You can enable or disable location services when you use our Service at any time, through your mobile device / browser settings.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><u><span style="font-size:19px;color:black;">Cookies</span></u></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">Cookies are files with a small amount of data, which may include an anonymous unique identifier. Cookies are sent to your browser from a web site and transferred to your device. We use cookies to collect information in order to improve our Services for you. Please note that none of the information stored on the cookie is personally identifiable.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. The help feature on most browsers provide information on how to accept cookies, disable cookies or to notify you when receiving a new cookie. If you do not accept cookies, you may not be able to use some features of our Website and Services.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><u><span style="font-size:19px;color:black;">Analytics</span></u></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">We use or may use third-party analytics services, such as Google Analytics and Facebook Analytics to evaluate your use of the Website, compile reports on activity, collect demographic data, analyze performance metrics, and collect and evaluate other information related to the Website. These third party service providers have their own privacy policies addressing how they use such information.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><u><span style="font-size:19px;color:black;">Google Analytics</span></u><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">Google Analytics is a web analytics service provided by Google, Inc., (&ldquo;Google&rdquo;) that employs cookies that collect, monitor and analyze information in order to increase our Website&apos;s functionality. The information generated by these cookies, such as time, place and frequency of your visits to our Website, including your IP address, is transmitted to Google&rsquo;s location in the US and stored there.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">For more information on how Google uses data it receives in connection with Google Analytics and your choices, you can visit www.google.com/policies/privacy/partners/.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><u><span style="font-size:19px;color:black;">Other tracking technologies</span></u></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">We may also use other tracking technologies, such as beacons and tags in order to provide a better service. These technologies usually work in conjunction with cookies. Web beacons (also referred to as pixels) and tags are elements included in web pages to enable companies to collect data, serve advertising, and provide related services, such as measuring ad effectiveness or preventing fake ad traffic. They do this by allowing communication between a web browser and a server. A web beacon is a small transparent image that is placed on a web page. A tag is a small piece of website code that is run by the web browser.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><u><span style="font-size:19px;color:black;">Third Party Advertising Cookies</span></u></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">We may engage and work with Service Providers and other third parties to serve advertisements on the Services and/or on Third-Party Services. Some of these ads may be tailored to your interest based on your browsing, across time, of the Services and elsewhere on the Internet, which may include use of data from cross-device usage, sometimes referred to as &quot;interest-based advertising&quot; and &quot;online behavioral advertising&quot; (&quot;Interest-based Advertising&quot;), which may include sending you an ad on a third-party service after you have left the Services (i.e., &quot;retargeting&quot;). Our advertisers&apos; and ad networks&apos; use of tracking technologies are governed by their own privacy policies.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><u><span style="font-size:19px;color:black;">Do Not Track Disclosure</span></u></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">We may track our users&rsquo; activities over time and across third party websites to provide targeted advertising. However, we do not respond to Do Not Track (&ldquo;DNT&rdquo;) signals at this time. In addition, some third-party sites also keep track of your browsing activities when they serve you content, which enables them to tailor what they present to you. Please review the privacy policies posted to all third-party websites to confirm if such websites respond to browser DNT settings.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><u><span style="font-size:19px;color:black;">Opting Out of Tracking Cookies</span></u></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">Many advertisers and service providers that perform advertising-related services for us and third parties participate in voluntary programs that provide tools to opt-out of such interest-based advertising such as the Digital Advertising Alliance&apos;s (&quot;DAA&quot;) Self-Regulatory Program for Online Behavioral Advertising. To learn more about how you can exercise certain choices regarding interest-based advertising for DAA members, visit http://www.aboutads.info/choices/, and http://www.aboutads.info/appchoices for information on the DAA&apos;s opt-out program for mobile apps. Some of these companies also are members of the Network Advertising Initiative (&quot;NAI&quot;). To learn more about the NAI and your opt-out options for their members, see&nbsp;</span><a href="http://www.networkadvertising.org/choices/"><span style="font-size:19px;color:#0B4CB4;">http://www.networkadvertising.org/choices/</span></a><span style="font-size:19px;color:black;">.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">Please be aware that, even if you are able to opt out of certain kinds of Interest-based Advertising, you may continue to receive other types of ads. Opting out only means that those selected, participating members should no longer deliver certain interest-based advertising to you but does not mean you will no longer receive any targeted content and/or ads (e.g., from other ad networks).</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><strong><span style="font-size:19px;color:black;">LOGGING IN THROUGH THIRD PARTIES</span></strong></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">You can log in and create an account on the Website using sign-in services such as Facebook and LinkedIn. These services will authenticate your identity and provide you the option to share certain personal information with us. If you connect to Facebook or LinkedIn, we may receive information like your name, profile picture, age range, language, email address, and friend / connections list.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><strong><span style="font-size:19px;color:black;">USE OF INFORMATION&nbsp;</span></strong></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">We use information collected about you, whether supplied directly by you or obtained through the use of tracking technologies as described herein, in any of the following ways:</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <ol style="list-style-type: decimal;margin-left:0in;">
                    <li><span style='font-family:"Times New Roman";'>Present the Website to you and allow you to use the Services including providing you with information or services you request from us.</span></li>
                    <li><span style='font-family:"Times New Roman";'>Send text messages, email communications or make telephone calls to you with respect to your employment application(s) and use of our Services.</span></li>
                    <li><span style='font-family:"Times New Roman";'>Communicate with you through telephone calls, email communications, text messages, in-app messaging, support chat, and via push notifications.</span></li>
                    <li><span style='font-family:"Times New Roman";'>Help administer and protect the security of the Website and Services.</span></li>
                    <li><span style='font-family:"Times New Roman";'>Develop, improve or enhance features of our Website and Services.</span></li>
                    <li><span style='font-family:"Times New Roman";'>Contact you regarding customer service and administrative issues.</span></li>
                    <li><span style='font-family:"Times New Roman";'>Improve customer service and user experience.</span></li>
                    <li><span style='font-family:"Times New Roman";'>Display and/or use aggregate information for advertising and marketing purposes.</span></li>
                    <li><span style='font-family:"Times New Roman";'>Make telephone calls and send text messages and/or email communications to you with information and offers.</span></li>
                    <li><span style='font-family:"Times New Roman";'>Track online behavior for behavioral advertising and other marketing purposes including compile anonymous statistical information and analysis.</span></li>
                    <li><span style='font-family:"Times New Roman";'>Notify you about changes to our Website or any Services we offer or provide though it.</span></li>
                    <li><span style='font-family:"Times New Roman";'>Send periodic e-mails (if at any time you would like to unsubscribe from receiving future e-mails, we include an option to unsubscribe at the bottom of each e-mail).&nbsp;</span></li>
                    <li><span style='font-family:"Times New Roman";'>In any other way we may describe when you provide the information.</span></li>
                    <li><span style='font-family:"Times New Roman";'>For any other purpose with your consent.</span></li>
                </ol>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><strong><span style="font-size:19px;color:black;">ACCESS TO THE INFORMATION</span></strong></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">We may disclose personal information that we collect or you provide as described in this Policy:</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <ol style="list-style-type: decimal;margin-left:0in;">
                    <li><span style='font-family:"Times New Roman";'>To our affiliates.</span></li>
                    <li><span style='font-family:"Times New Roman";'>To contractors, staffing agency partners, service providers, business partners and other third parties we use to support our business and make the Website and/or Services available.</span></li>
                    <li><span style='font-family:"Times New Roman";'>To a buyer or other successor in the event of a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of the RN500&rsquo;s assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which personal information held by RN500 about our Website visitors and customers is among the assets transferred.</span></li>
                    <li><span style='font-family:"Times New Roman";'>To fulfill the purpose for which you provide it including for the purpose of connecting applicants with staffing agencies.&nbsp;</span></li>
                    <li><span style='font-family:"Times New Roman";'>To enforce or apply this Policy, or our Terms of Service, Short Code Terms of Service, CCPA Notice, and any other agreements, including for billing and collection purposes.</span></li>
                </ol>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">We may also disclose information collected from you through this Website in order to: (i) comply with applicable laws; (ii) respond to government inquiries; and (iii) protect the rights or property of RN500 or visitors to this Website.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">We do not sell or share your personal information with other individuals or organizations except to the extent required to provide the Services and to connect you with appropriate job opportunities.&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><strong><span style="font-size:19px;color:black;">LINKS TO THIRD PARTY WEBSITES&nbsp;</span></strong></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">Our Website may contain links to third party websites. These links are provided only for your convenience and you are free to use them, but you do so at your own risk. We do not control these third parties&apos; or their websites. The third parties who operate such websites may use tracking technologies. Please read the privacy policies of these third party websites carefully before browsing or providing any information on such websites. We are not responsible for your activities or any collection or tracking of your information on such sites.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><u><span style="font-size:19px;color:black;">Telephone Consumer Protection Act</span></u></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">We may seek your consent to receive text messages from us, our affiliates, service providers, business partners and other third parties we use to support our business and make the Services available to you in accordance with the rules under the Telephone Consumer Protection Act (&quot;TCPA&quot;). While we do not believe our text messages qualify as telemarketing text messages, nonetheless, to comply with the TCPA consent requirements regarding telemarketing messages, when we request that you provide your phone number and/or permission to contact you, we will request your prior express written consent to send you text messages to the phone number you provide. Please note that you can continue accessing our Website or using the Services without providing your prior express written consent for TCPA purposes and that merely accessing our Website or using the Services without providing your prior express written consent when prompted does not constitute your consent to receive such text messages.&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><u><span style="font-size:19px;color:black;">Opting-Out from Email Communications&nbsp;</span></u></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">We may use your Personal Information to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. If you no longer wish to receive these communications, you may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send. However, you may continue to receive e-mail communications from us for no more than ten business days from the time we receive your unsubscribe request. Please note that we can only control our own mailing list and policies. Third party advertisers that maintain their own mailing lists may send communications that advertise our products or services; and you may need to contact those parties directly in order to stop receiving their e-mail communications.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><u><span style="font-size:19px;color:black;">Opting-Out from Text Messages</span></u></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">If you have participated in any text message or short code campaign, you may opt-out by texting &quot;<strong>STOP</strong>&quot; to the short code provided in that message. If you need any assistance, text &quot;<strong>HELP</strong>&quot; to the short code provided in the message. Message and data rates may apply.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">Certain administrative communications, including e-mails, text messages and telephone calls, are necessary in order to deliver our Services. If you agree to use our Services, you agree to receive these administrative communications.&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><strong><span style="font-size:19px;color:black;">SECURITY</span></strong></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">The security of your Personal Information is important to us, and we implement a variety of security measures in an effort to maintain the safety of the information we store, and in order to protect it from unauthorized access, destruction, use, modification, or disclosure.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">Unfortunately, however, no data transmission over the Internet can be guaranteed to be 100% secure. Accordingly, while we strive to protect your personal information, we cannot guarantee or warrant the security of any information you transmit to us, or to or from our online products or services. You transmit all such information at your own risk. We are not responsible for circumvention of any privacy settings or security measures contained on the Website.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><strong><span style="font-size:19px;color:black;">CHILDREN&apos;S PRIVACY</span></strong></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">Our Service is not intended for anyone under the age of 18.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">We do not knowingly collect personal information from anyone under 13. If you are a parent or guardian and you learn that your children have provided us with Personal Information, please contact us. If we become aware that we have collected personal information from a child under age 13 without verification of parental consent, we take steps to remove that information from our servers.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><strong><span style="font-size:19px;color:black;">CALIFORNIA PRIVACY RIGHTS</span></strong></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">Due to the nature of our business, the only Personal Information we collect through our Service that potentially gives rise to rights under the CCPA are anonymous device identifiers used for analytics and the functioning of the website. Accordingly, we are unable to fulfill requests to exercise any of the consumer rights prescribed by the CCPA because we cannot verify a consumer&rsquo;s identity as required by the CCPA without collecting additional Personal Information in a manner that would be contrary to the CCPA&rsquo;s requirements.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">We do not &ldquo;sell&rdquo; personal information that we collect from you, as &ldquo;sell&rdquo; is defined in the California Consumer Privacy Act (CCPA). We work with service providers and partner with advertising companies that use cookies and other tracking technologies to collect information about your visits to our website and third-party sites, and then use that information to deliver advertisements relevant to your interests. There is not yet a consensus as to whether third party cookies and tracking technologies associated with our websites and mobile apps constitute a &ldquo;sale&rdquo; of your Personal Information as defined by the CCPA, and we do not treat this third party information collection as a &ldquo;sale&rdquo; of your Personal Information by us. You may learn more about tracking cookies and how to opt out of cookies and other tracking technologies https://RN500.com/privacy-policy.html#opt-out.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">Under California&rsquo;s Shine the Light law, pursuant to Section 1798.83 of the California Civil Code, residents of California have the right to obtain certain information about the types of personal information that companies with whom they have an established business relationship (and that are not otherwise exempt) have shared with third parties for direct marketing purposes during the preceding calendar year, including the names and addresses of those third parties, and examples of the types of services or products marketed by those third parties. If you wish to submit a request pursuant to Section 1798.83, please contact RN500 at&nbsp;support@RN500.com&nbsp;or:</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">RN500, Inc.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">445, Park Avenue,&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">Manhattan, NY 10022. USA.&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">Telephone: +1-917-806-5507.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">Email:&nbsp;support@RN500.com</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">Any such request must include &ldquo;California Privacy Rights Request&rdquo; in the first line of the description and include your name, street address, city, state, and ZIP code. Please note that we are only required to respond to one request per customer each year, and we are not required to respond to requests made by means other than through this email address or mail address.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><strong><span style="font-size:19px;color:black;">CONTACT US</span></strong></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">&nbsp;</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;'><span style="font-size:19px;color:black;">If you have any questions about this Privacy Policy, please contact us at&nbsp;support@RN500.com.</span></p>
                <p style='margin:0in;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><span style="font-size:19px;">&nbsp;</span></p>
            </div>
        </div>


    </div>
</section>